### ISSUE TITLE
Downloading images

### ISSUE THREAD

**Issue by xinlin-chen** [jbilskie/BME547_final#102]
@jbilskie for an invalid input to download_images, only one output, status, is returned. Can you also return an empty dict or list for img_info?

**Comment by xc130** [comment]
Also, for an invalid input to download_images, only one output, status, is returned. Can you also return an empty dict or list for img_info?

**Comment by xc130** [comment]
Also, it appears that download_images never calls download_image for the inputs in my first comment, because "Asking server to download image" doesn't print.

**Comment by xinlin-chen** [comment]
Actually, I'll just make a couple minor edits if that's OK
