### ISSUE TITLE
Client/server testing

### ISSUE THREAD

**Issue by xinlin-chen** [jbilskie/BME547_final#11]

**Comment by xinlin-chen** [comment]
@kevinmchu can you make it so validate_input also checks if a field exists? I'm testing empty dictionaries inputs to process_new_user

**Comment by kevinmchu** [comment]
I am assuming that when the user clicks upload, the GUI sends a dictionary with all the fields to the server. If the user fails to enter any information, I assume that the GUI still sends a dictionary with all the proper fields but with empty values. The validate_input function makes sure the user entered something for each field.

**Comment by kevinmchu** [comment]
@xc130 There are going to be a lot of functions in the server, so I can split the unit tests with you. I am thinking that you can test the functions I wrote (anything that has to do with registering a user, uploading images, and processing images), and I can test Jessica's functions.

**Comment by xinlin-chen** [comment]
@kevinmchu  I'm working my way through them. My main problem is that based on past experience, any unit testing involving MongoDB is going to be a pain :(

**Comment by xinlin-chen** [comment]
@kevinmchu some functions don't return anything so I'm not writing their test code for now - could you rewrite them to return something testable, and/or assign to global variables as well as the database so that I can test more easily? :)

**Comment by kevinmchu** [comment]
@xc130 I assume you are referring to `register_new_user` and `upload_image`. In these functions, we're uploading information to the database, so I don't see a need to return anything. The way I've been testing Jessica's functions is to create fake users and make sure I can read their information from a database. Then after the assert statement, I write a line to delete the user from the database. You can see an example of this in the function `test_exist_input` in `test_server.py`.
