### ISSUE TITLE
Converting np.array into base64 string

### ISSUE THREAD

**Issue by kevinmchu** [jbilskie/BME547_final#18]
To process the image, I convert the base64 string into an np.array and perform processing. I also must convert the processed np.array back to a base64 string so it can be stored in the database. The only solution I could think of is to save the processed np.array and then read the image back in as a base64. Is there a more elegant way to do this that doesn't involve saving and loading images?

All the relevant code can be found under the kmc/process_images branch.

**Comment by dward2** [comment]
Would you please point me to some client code that I can run that would allow me to step through your code to understand your question?  I can run your `server.py` code to generate a local server.  But, what code do you have that would then make the necessary calls to the server to see your process?

**Comment by kevinmchu** [comment]
`client.py` makes calls to the server.

**Comment by dward2** [comment]
Upon running `client.py`, I get the following error:
```
Traceback (most recent call last):
  File "D:\Program Files\JetBrains\PyCharm 2018.2.4\helpers\pydev\pydevd.py", line 1664, in <module>
    main()
  File "D:\Program Files\JetBrains\PyCharm 2018.2.4\helpers\pydev\pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "D:\Program Files\JetBrains\PyCharm 2018.2.4\helpers\pydev\pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Program Files\JetBrains\PyCharm 2018.2.4\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/ClassRepos/SentinalAssign/bilskie_chen_chu/client.py", line 110, in <module>
    process_image("user1", "structure.jpg", "Log Compression")
  File "D:/ClassRepos/SentinalAssign/bilskie_chen_chu/client.py", line 89, in process_image
    b64_string = read_img_as_b64(filename)
NameError: name 'read_img_as_b64' is not defined

Process finished with exit code 1
```
Please fix that and I'll take another look.

**Comment by kevinmchu** [comment]
I committed the fixed code.

**Comment by dward2** [comment]
I just pushed up a new branch called `kmc/process_images_daw`.  In it, there is a file called `daw.py`.  It has the function shown here:

https://github.com/jbilskie/BME547_final/blob/2fec3be315f854d3a3a062cf54c0c2e311f168b5/daw.py#L73-L102

It uses the skimage.io.imsave function to "save" the nd.array image into the bytes that would be saved as a file on disk.  But, instead of saving those bytes onto disk, they are redirected into a BytesIO buffer, and those bytes can then be converted into your base64 string.

Take a look and let me know if you have any questions.

**Comment by kevinmchu** [comment]
This worked for me. Thank you for your help.

**Comment by kevinmchu** [comment]
I am testing the  `image_to_b64` function in `image.py` under the kmc/test_image branch. This test converts an image into a base64 string and then compares it to the expected base64, which is stored in a text file. However, I am receiving an assertion error because the strings are not the same, even when I use the same image. I think this might have to do with the way the BytesIO buffer is set up. Is there a way I can save the image as a specific type in the BytesIO buffer?

**Comment by dward2** [comment]
When I run the test below on my computer, I do not receive any errors.
https://github.com/jbilskie/BME547_final/blob/73774f1dd7628f428d120d64c7ad4d129165eedf/test_image.py#L137

Can you verify that this is what you are getting your error on?  And, if so, grab a screen shot for me?

**Comment by kevinmchu** [comment]
It turns out that the base64 string saved to the buffer is different from the string that I read from the image file. I changed the test so that I read in the string that is specific to the buffer.
