### ISSUE TITLE
Get original and processed images from server

### ISSUE THREAD

**Issue by kevinmchu** [jbilskie/BME547_final#23]

**Comment by kevinmchu** [comment]
@jbilskie Your `exist_input` function throws a DoesNotExist error when I try to retrieve a user that does not exist in the database. Can I change the code to handle the error?

**Comment by kevinmchu** [comment]
@jbilskie Your `process_image_download` function does not appear to return img_info when the status code is anything but 200. However, your call to `process_image_download` in `image_download` always expects `process_image_download` to return two arguments. I am modifying `process_image_download` to return an empty dictionary if the status code indicates an invalid request.

**Comment by jbilskie** [comment]
Ok, did you make these changes or would you like me to fix these? @kevinmchu

**Comment by kevinmchu** [comment]
I made them.

**Comment by jbilskie** [comment]
Ok thanks.
