### ISSUE TITLE
Modular code for GUI/GUI testing

### ISSUE THREAD

**Issue by xinlin-chen** [jbilskie/BME547_final#29]
Is it acceptable to create all the GUI widgets in one function, (e.g. the display_window function in the GUI lecture), or should we split them up? Also, do we only have to test whether the GUI successfully sends and receives information, or do we also have to test whether individual labels work as designed?

**Comment by dward2** [comment]
Yes, you can create all of the GUI widgets in one function, unless you feel there is a good reason to separate them.  If you do want to separate them, you can send the window variable as a parameter in a function call.

In terms of testing, look at this pseudo-code example:
```
def create_window():

    def start_upload():
        code for getting filename from GUI
        upload_to_server(filename)

    root = Tk()
    code to add some GUI widgets 
    button = ttk.Button(root, text='Upload File', command='start_upload')
    more code as needed
    root.mainloop()

def upload_to_server(filename):
    function_validate_filename_is_image(filename)
    b64_string = function_to_encode_image(filename)
    function_to_make_server_request(b64_string)
    return
```
The `create_window()` function creates and displays the GUI.  The `start_upload()` function is connected to the "Upload File" button.  The `start_upload()` file does the minimum necessary to send information from the GUI to a separate function that can be independent of the GUI.  In this case, the function is `upload_to_server()`.  `upload_to_server()`, or any functions called from here if it is well modular, should have unit tests associated with them as they are independent of the GUI.

You should manually test the GUI to make sure its functionality works, as that is something that is also important.  But, we don't have unit tests for that.

Does that answer your questions?

**Comment by xinlin-chen** [comment]
Thank you, that answers my questions. I also wanted to ask - when we ask for an image, is it sufficient to have the user input an image path/comma-separated list of paths, or do we need to have a Finder window (or the Windows equivalent) pop up to help them select the images?

**Comment by dward2** [comment]
It is sufficient to allow the user to input the image name into the GUI via a text input.  Note, if you are using `tkinter` there is an easy dialog for finding files:  <https://tkdocs.com/tutorial/windows.html#dialogs>.  You are not required to use it, but it is pretty easy.

**Comment by dward2** [comment]
Of course, that dialog won't work if you are asking the user what images from the database to access.  So, there text entry would certainly be easier, as long as you somehow list out the images that the user can choose from.

**Comment by xinlin-chen** [comment]
Thank you. One final question - should our processing steps take the form of radio buttons or check boxes? Would we want to let users choose multiple options?

**Comment by dward2** [comment]
That is your call.  In general, when other students have been asking, I have said that you only need to do one processing step at a time, but that you do need to give the user the ability to do a second processing step on an already processed image.  So, if you want to go ahead and let them select multiple steps at once, or if you want them to do it sequentially, that is your design decision.

**Comment by xinlin-chen** [comment]
@dward2 Thanks. We decided to go about things sequentially. Does this mean that we can ask the user to download the processed image and then upload from the downloaded image path for further processing?

**Comment by dward2** [comment]
No, ideally, the user shouldn't need to download a processed image, and then re-upload it.  They should be able to choose a processed image on the server and ask to have it processed again.  Now, if behind the scenes, the file is downloaded, then re-uploaded with a new processing request, that is fine as long as that is transparent to the user.  If it happens in the background, that is okay.  But, if the image is already on the server, there should be a relatively straight forward way of using it directly.

**Comment by jbilskie** [comment]
@xc130 I can make a function today to handle this correctly. I'm going to make the Boolean processed array given be all the steps to be performed on the image like you correctly interpreted and I did not haha.
