### ISSUE TITLE
Input/output handling

### ISSUE THREAD

**Issue by xinlin-chen** [jbilskie/BME547_final#3]

**Comment by xinlin-chen** [comment]
@kevinmchu @jbilskie Right now, the images will display in the GUI as a slideshow. The number of labels and list entries (the list posted to the server) initiated are equal to the number of images processed + wrong pathnames. If a pathname is wrong, the list entry is just an empty string ('') and the label will say "Image not found" in the window. The server should ideally return a list of equal length, and also return an empty string if the original list entry was empty.

**Comment by xinlin-chen** [comment]
@kevinmchu which might also mean it's necessary to validate that the "image" field in img_info isn't empty before trying to convert it from a b64 string

**Comment by kevinmchu** [comment]
I will fix this.

**Comment by kevinmchu** [comment]
I finished writing the code to validate the "image" field.

**Comment by xinlin-chen** [comment]
@kevinmchu if it doesn't take too much time, in validate_input and/or process_image_upload, can you make it so the message can tell if multiple fields are empty (e.g. "Fields username, filename cannot be empty.") ?

**Comment by xinlin-chen** [comment]
@kevinmchu @jbilskie I'm going to change b64_to_image to work with the GUI

**Comment by kevinmchu** [comment]
@xc130 Can you write a separate function? Changing b64_to_image might mess up some of the code in the client and server.

**Comment by xinlin-chen** [comment]
@kevinmchu I actually meant that it doesn’t return a np array that can be read as an image, so that would require changing the function itself

**Comment by kevinmchu** [comment]
@xc130 Right, but the functions to process the image and get the size depend on `b64_to_image`, I don't want to mess up those functions. What do you need to display the image in the GUI?

**Comment by kevinmchu** [comment]
@xc130 You can use this function Dr. Ward wrote to display a base64 string as an image

```
def view_b64_image(base64_string):
    image_bytes = base64.b64decode(base64_string)
    image_buf = io.BytesIO(image_bytes)
    i = mpimg.imread(image_buf, format='JPG')
    plt.imshow(i, interpolation='nearest')
    plt.show()
    return
```

**Comment by xinlin-chen** [comment]
@kevinmchu ok cool, I haven’t made any changes yet. What is actually being outputted out of b64_to_image?

**Comment by kevinmchu** [comment]
An np.array
