### ISSUE TITLE
Get images from GUI

### ISSUE THREAD

**Issue by xinlin-chen** [jbilskie/BME547_final#39]
Return a status code in the client code to tell the GUI when images are successfully/unsuccessfully uploaded to the server

**Comment by jbilskie** [comment]
This is done in functions seen in client.

upload_image returns a status. @kevinmchu created upload_images to look through a list of files.

process_image returns status and requires the image you wish to upload. If you desire to process an image already in the database, you need to download_image() and then use that in process_image.

download_image returns status and img_info containing image and metadata

What else is needed from the GUI perspective. @xc130

**Comment by xinlin-chen** [comment]
@jbilskie so right now it seems like some functions only print the status and message without returning anything - I can redo those. Otherwise, I think we just need a function that sends multiple files as a zip.

**Comment by jbilskie** [comment]
the functions in the client only return status (except for download_image but do whatever it is they are meant to so they put an image in the database (either processed or not) @xc130 . What do you need from them? The download_image gives you all the metadata including the image bits.

**Comment by jbilskie** [comment]
What do you want them to return?

**Comment by jbilskie** [comment]
This is finished now correct? @xc130

**Comment by xinlin-chen** [comment]
Yep
