### ISSUE TITLE
GUI histogram display

### ISSUE THREAD

**Issue by xinlin-chen** [jbilskie/BME547_final#45]
Would the Pillow Image.histogram() function create the correct histograms of color/intensity values? Also, do we want histogram display to appear/disappear according to user preferences as well?

**Comment by dward2** [comment]
There are many different packages that provide this function.  If the Pillow version gives an image historgram as described in <https://en.wikipedia.org/wiki/Image_histogram>, then it would be fine.

It is your design decision whether to always display a historgram, or only display if asked by the user.  But, your GUI has to provide the ability to see a histogram.  But, how and when is up to you.

**Comment by xinlin-chen** [comment]
Do we have to test the histograms with unit tests or just test that they show up and appear to be correct?

**Comment by dward2** [comment]
I would write a test of your function that calculates the histogram.  On a one-time basis, run a historgram on a simple image and save the result.  Then, for your unit test, you can do the histogram on this sample image, and compare the results against the saved result (or the first 10 to 20 characters).  While this may seem silly to run a function, and then test it by running it again.  But, it can make sure that in the future, any changes don't impact its functioning.
