### ISSUE TITLE
Server - Test Image Upload and Processing

### ISSUE THREAD

**Issue by kevinmchu** [jbilskie/BME547_final#46]
Write unit tests for 
`process_new_user`
`register_new_user`
`validate_input`
`process_image_upload`
`get_img_size`
`upload_image`
`process_process_image`
`run_image_processing`
`equalize_histogram`
`stretch_contrast`

**Comment by kevinmchu** [comment]
@xc130 As written, `test_process_new_user` tests the status message as well as the code. As I write the function to check whether the user to add already exists, I want to write a status message that indicates the user already exists. When I do this, pytest fails because `test_process_new_user` expects the status message to be "Field username cannot be empty." Can I change the code so that we are also passing the expected status message to `test_process_new_user`?

**Comment by xinlin-chen** [comment]
@kevinmchu  go ahead. I'll add a test case to see that that works.

**Comment by xinlin-chen** [comment]
@kevinmchu also going to change the 'try' code in check_user_exists (currently always throws an exception)

**Comment by kevinmchu** [comment]
@xc130 Okay.

**Comment by kevinmchu** [comment]
Done. #100
