### ISSUE TITLE
Client/Server - Test Image Module

### ISSUE THREAD

**Issue by kevinmchu** [jbilskie/BME547_final#47]
Write unit tests for
`read_img_as_b64`
`save_b64_img`
`b64_to_image`
`image_to_b64`
`unzip`

**Comment by kevinmchu** [comment]
@xc130 I identified a couple of potential bugs in the `unzip` function:

1) As written, the function outputs a success of False if it encounters any file within the zip file that contains the regular expression ._
Because zip files created in Mac contain Mac files, when run on Mac `unzip` will always give a success of False. I'm not sure if this is the intended behavior, but I just wanted to make you aware.

2) While the regular expression does disregard the Mac files, it also fails to unzip if the name of the zip file or the files in the unzip contain an underscore.

**Comment by xinlin-chen** [comment]
@kevinmchu so it now loops through the names of the files in the zip archive and only puts a false if there is nothing in the archive or it fails to extract data from a filename that doesn't have '._' in the name. I updated the second test_unzip test case and put in a bit of code to strip whitespace from a string

**Comment by jbilskie** [comment]
@kevinmchu I added a function is_b64() to image.py. Could you write a small test for that where ever you have these tests since they fall in the same category? Otherwise, I can write it, I would assume they are in test_image.py, correct?

**Comment by kevinmchu** [comment]
Done via #95.
