### ISSUE TITLE
Testing base 64 conversions

### ISSUE THREAD

**Issue by kevinmchu** [jbilskie/BME547_final#49]
The `image.py` module in the master branch contains functions that convert an image to and from base64. I thought about testing these functions by creating test images that are 1x1 pixel. However, when I did this the base64 representation of the images is still quite long, and it would look quite messy to include this string in unit tests. Is there a more elegant way of testing `image.py`?

**Comment by kevinmchu** [comment]
Actually, I set up the test to read in the expected string from a text file, and this seemed to work.

**Comment by dward2** [comment]
Just as a comment, you don't necessarily need to do an `assert` against the entire string.  You could just assert against the first 10 or 20 digits of the string.  For example:
```
answer = "/9j/4AAQSkZJRgABAQEA"
x = encode_image_file_to_b64_string("test01.jpg")
    assert x[0:20] == answer
```
