### ISSUE TITLE
GUI Compatibility with Windows

### ISSUE THREAD

**Issue by kevinmchu** [jbilskie/BME547_final#52]
We are experiencing some compatibility issues when running `gui.py` on Windows. I was able to run the GUI on my Mac, but I obtained a warning that might be related to the issue.

```
gui.py:9: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'MacOSX' by the following code:
  File "gui.py", line 8, in <module>
    from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
  File "/Users/kevinmchu/anaconda3/lib/python3.7/site-packages/matplotlib/backends/__init__.py", line 16, in <module>
    line for line in traceback.format_stack()


  matplotlib.use("TkAgg")
```

How can we fix this?

**Comment by kevinmchu** [comment]
@jbilskie Could you post your error?

**Comment by dward2** [comment]
You can read more here:
<https://matplotlib.org/faq/usage_faq.html#what-is-a-backend>
See if this gives you any guidance.  I will have some time later tonight, or tomorrow afternoon, to clone your repo and see what happens on my Windows computer.

**Comment by jbilskie** [comment]
I'm running on Windows. I don't get an error necessarily. When I hit "display" to show the image after uploading from a valid path, nothing comes up and where the image should be it says "Image not found" which appears to happen in the except statement on line 316 of gui.py

**Comment by xinlin-chen** [comment]
I can change the label to show something different if the actual problem is that the image can’t be processed.

**Comment by dward2** [comment]
@xc130 @kevinmchu @jbilskie I downloaded your latest code on the master branch (as of about 1:30 pm).  When I start up `server.py` (I change the MongoDB connect path to my MongoDB server so as not to mess up your database) and then run `gui.py`, I am able to enter a user name, a file name, and then click Upload.  Then, when I click on the Display Images checkbox, a window opens up and shows the picture I uploaded.  So, I am not have the same issue.  Perhaps it has been fixed?

**Comment by dward2** [comment]
FYI, I'm running Windows and running in PyCharm

**Comment by xinlin-chen** [comment]
Does it also show the histograms for that image? I don't think I worked on gui.py since yesterday, but we can try testing it again on Windows platforms.

**Comment by dward2** [comment]
Yes, here is what I saw:
![image](https://user-images.githubusercontent.com/40216703/56474656-b21b4580-644a-11e9-9f47-9153cb512b9e.png)

**Comment by jbilskie** [comment]
It works on mine now... not sure what changed. @xc130

**Comment by jbilskie** [comment]
![image](https://user-images.githubusercontent.com/46608628/56477798-7c408600-6477-11e9-8d0a-9426a598ba45.png)
