### ISSUE TITLE
Delete Users from Database

### ISSUE THREAD

**Issue by jbilskie** [jbilskie/BME547_final#65]
@xc130 thinks it'd be useful to have a function to delete users from the database.

**Comment by xinlin-chen** [comment]
Not users, images

**Comment by xinlin-chen** [comment]
I think I’ve uploaded about 10 copies of Orion.jpg to 2 users already

**Comment by jbilskie** [comment]
I have manually cleared the database tonight. Regardless, now there is a function for deleting users. I could make one for deleting an image within a specified user too if you wish... @xc130
