### ISSUE TITLE
Database creation

### ISSUE THREAD

**Issue by xinlin-chen** [jbilskie/BME547_final#7]

**Comment by jbilskie** [comment]
To connect to database:
from pymodm import connect
connect("mongodb+srv://jmb221:bme547@bme547-kcuog.mongodb.net/test?retryWrites=true")

**Comment by jbilskie** [comment]
@kevinmchu @xc130

**Comment by jbilskie** [comment]
@kevinmchu Are you able to access the database still. I went to dinner and came back and now I get a 500 error every time I try to run user.save.

**Comment by kevinmchu** [comment]
The previous version of server.py did not connect database, but this is fixed in the most recent commit #38.
