### ISSUE TITLE
Client Testing

### ISSUE THREAD

**Issue by kevinmchu** [jbilskie/BME547_final#84]
@jbilskie Which functions are you testing?

**Comment by jbilskie** [comment]
Just check_file_list and zipdir... in this initial commit that now fails with whatever changes you just made its only check_file_list @kevinmchu

**Comment by kevinmchu** [comment]
What is the error?

**Comment by jbilskie** [comment]
Its an import error. So I don't actually think it has anything to do with what you just committed. Haha I'm looking into. Its odd because I don't get any errors locally but then when I push it up Travis CI fails. @kevinmchu

**Comment by kevinmchu** [comment]
@jbilskie I had the same problem when testing the functions that upload images to the database. Strangely, the tests that failed in Travis when I initially committed them worked a few hours later. However, I think this may have been a database specific issue.

**Comment by jbilskie** [comment]
Finished in commit #116
