### ISSUE TITLE
GUI testing

### ISSUE THREAD

**Issue by xinlin-chen** [jbilskie/BME547_final#9]

**Comment by xinlin-chen** [comment]
@jbilskie there's no need to test the editing_window() or display_images functions - they both just create GUI widgets/Tk windows

**Comment by xinlin-chen** [comment]
@jbilskie display_histograms, show_next, show_prev also deal with widgets

**Comment by jbilskie** [comment]
What functions need tested then? @xc130 ....
only process_img_paths, get_img_data, and upload_to_server ?

**Comment by xinlin-chen** [comment]
@jbilskie I'm not sure if histograms need to be tested yet. Right now, only those. There will also be a function in gui.py that uses the download_image function in client.py. I'll rewrite the download_image function so it returns the image and status info instead of just printing it.

**Comment by xinlin-chen** [comment]
@jbilskie also, an image might have multiple processing steps requested, so it might be better to have a list of booleans as opposed to a string as the input to download_image

**Comment by xinlin-chen** [comment]
@jbilskie functions that need to be tested:
convert_inputs
process_img_paths
get_img_data
get_file_list
resize_img_dim
calc_histograms

**Comment by kevinmchu** [comment]
@jbilskie What is the status on this?

**Comment by jbilskie** [comment]
Working on it. One is done. Don't worry I'll stay up all night if I have to getting these done :) @kevinmchu

**Comment by jbilskie** [comment]
Finished in #121
